-- ============================================================================
-- migration: initial schema for 10xcards application
-- description: creates core tables for flashcard generation and management
-- tables affected: generations, flashcards, generation_error_logs
-- special notes:
--   - users table is managed by supabase auth and is not created here
--   - includes rls policies for all tables with user_id based access control
--   - includes trigger for auto-updating flashcards.updated_at timestamp
-- ============================================================================

-- ============================================================================
-- function: auto update timestamp
-- purpose: automatically sets updated_at to current timestamp on row updates
-- usage: attached as trigger to tables that need updated_at tracking
-- ============================================================================
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ============================================================================
-- table: generations
-- purpose: stores metadata about ai-powered flashcard generation sessions
-- access: users can only access their own generation records
-- ============================================================================
create table generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  generated_count integer not null,
  -- tracks how many flashcards were accepted without edits
  accepted_unedited_count integer,
  -- tracks how many flashcards were accepted after editing
  accepted_edited_count integer,
  -- hash of source text to detect duplicate generation attempts
  source_text_hash varchar not null,
  -- length validation ensures reasonable input size (1k-10k chars)
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  -- duration in milliseconds
  generation_duration integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- index for efficient user-specific queries
create index idx_generations_user_id on generations(user_id);

-- enable row level security
alter table generations enable row level security;

-- rls policy: allow authenticated users to view their own generations
create policy "authenticated users can select own generations"
  on generations
  for select
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: allow anonymous users to view their own generations
create policy "anonymous users can select own generations"
  on generations
  for select
  to anon
  using (auth.uid() = user_id);

-- rls policy: allow authenticated users to insert their own generations
create policy "authenticated users can insert own generations"
  on generations
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- rls policy: allow anonymous users to insert their own generations
create policy "anonymous users can insert own generations"
  on generations
  for insert
  to anon
  with check (auth.uid() = user_id);

-- rls policy: allow authenticated users to update their own generations
create policy "authenticated users can update own generations"
  on generations
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- rls policy: allow anonymous users to update their own generations
create policy "anonymous users can update own generations"
  on generations
  for update
  to anon
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- rls policy: allow authenticated users to delete their own generations
create policy "authenticated users can delete own generations"
  on generations
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: allow anonymous users to delete their own generations
create policy "anonymous users can delete own generations"
  on generations
  for delete
  to anon
  using (auth.uid() = user_id);

-- ============================================================================
-- table: flashcards
-- purpose: stores individual flashcard data with source tracking
-- access: users can only access their own flashcards
-- source types:
--   - 'ai-full': generated by ai and accepted without modifications
--   - 'ai-edited': generated by ai but modified by user before accepting
--   - 'manual': created entirely by user without ai assistance
-- ============================================================================
create table flashcards (
  id bigserial primary key,
  -- front side of flashcard (question/prompt)
  front varchar(200) not null,
  -- back side of flashcard (answer/content)
  back varchar(500) not null,
  -- tracks how this flashcard was created
  source varchar not null check (source in ('ai-full', 'ai-edited', 'manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- optional reference to generation session (null for manual cards)
  -- on delete set null: if generation is deleted, flashcard remains but loses reference
  generation_id bigint references generations(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade
);

-- indexes for efficient queries
create index idx_flashcards_user_id on flashcards(user_id);
create index idx_flashcards_generation_id on flashcards(generation_id);

-- trigger to automatically update updated_at timestamp on modifications
create trigger update_flashcards_updated_at
  before update on flashcards
  for each row
  execute function update_updated_at_column();

-- enable row level security
alter table flashcards enable row level security;

-- rls policy: allow authenticated users to view their own flashcards
create policy "authenticated users can select own flashcards"
  on flashcards
  for select
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: allow anonymous users to view their own flashcards
create policy "anonymous users can select own flashcards"
  on flashcards
  for select
  to anon
  using (auth.uid() = user_id);

-- rls policy: allow authenticated users to create their own flashcards
create policy "authenticated users can insert own flashcards"
  on flashcards
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- rls policy: allow anonymous users to create their own flashcards
create policy "anonymous users can insert own flashcards"
  on flashcards
  for insert
  to anon
  with check (auth.uid() = user_id);

-- rls policy: allow authenticated users to modify their own flashcards
create policy "authenticated users can update own flashcards"
  on flashcards
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- rls policy: allow anonymous users to modify their own flashcards
create policy "anonymous users can update own flashcards"
  on flashcards
  for update
  to anon
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- rls policy: allow authenticated users to delete their own flashcards
-- warning: this permanently removes flashcard data
create policy "authenticated users can delete own flashcards"
  on flashcards
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: allow anonymous users to delete their own flashcards
-- warning: this permanently removes flashcard data
create policy "anonymous users can delete own flashcards"
  on flashcards
  for delete
  to anon
  using (auth.uid() = user_id);

-- ============================================================================
-- table: generation_error_logs
-- purpose: tracks failed flashcard generation attempts for debugging and monitoring
-- access: users can only access their own error logs
-- note: error logs are append-only; users cannot modify or delete them
-- ============================================================================
create table generation_error_logs (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  -- hash of source text that caused the error
  source_text_hash varchar not null,
  -- length validation ensures reasonable input size (1k-10k chars)
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  -- standardized error code for categorization
  error_code varchar(100) not null,
  -- detailed error message for debugging
  error_message text not null,
  created_at timestamptz not null default now()
);

-- index for efficient user-specific error log queries
create index idx_generation_error_logs_user_id on generation_error_logs(user_id);

-- enable row level security
alter table generation_error_logs enable row level security;

-- rls policy: allow authenticated users to view their own error logs
create policy "authenticated users can select own error logs"
  on generation_error_logs
  for select
  to authenticated
  using (auth.uid() = user_id);

-- rls policy: allow anonymous users to view their own error logs
create policy "anonymous users can select own error logs"
  on generation_error_logs
  for select
  to anon
  using (auth.uid() = user_id);

-- rls policy: allow authenticated users to insert their own error logs
create policy "authenticated users can insert own error logs"
  on generation_error_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- rls policy: allow anonymous users to insert their own error logs
create policy "anonymous users can insert own error logs"
  on generation_error_logs
  for insert
  to anon
  with check (auth.uid() = user_id);

-- note: update and delete policies are intentionally omitted
-- error logs should be immutable for audit trail purposes
-- if modification is needed in the future, add policies here
